### ISSUE TITLE
__wxConfig is not defined

### ISSUE THREAD

**Issue by AutismTl** [r3x5ur/wxapkg-unpacker#12]
**Describe the bug**
/Users/tangliang/miniapp/wxapkg-unpacker/node_modules/vm2/lib/vm.js:287
				throw bridge.from(e);
				^
ReferenceError [Error]: __wxConfig is not defined
    at vm.js:4:3313
    at vm.js:4:6124
    at Script.runInContext (node:vm:139:12)
    at VM.runScript (/Users/tangliang/miniapp/wxapkg-unpacker/node_modules/vm2/lib/vm.js:285:18)
    at VM.run (/Users/tangliang/miniapp/wxapkg-unpacker/node_modules/vm2/lib/vm.js:503:16)
    at /Users/tangliang/miniapp/wxapkg-unpacker/packages/unpacker/src/wuJs.js:41:8
    at /Users/tangliang/miniapp/wxapkg-unpacker/packages/unpacker/src/wuLib.js:105:10
    at agent (/Users/tangliang/miniapp/wxapkg-unpacker/packages/unpacker/src/wuLib.js:66:17)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**To Reproduce**/**复现过程**
macos按照步骤操作

**Expected behavior**/**预期结果**
正常

**Actual behavior**/**实际结果**
异常
**Screenshots**/**相关截图**

**运行环境、版本信息**<br/>
**Desktop (please complete the following information):**
 - OS: macos
 - NodeJS: nodejs
 - Version 16.1

**Additional context**/**其他描述**

**Comment by r3x5ur** [comment]
#15
